object Depends {
    const val kotlin = "org.jetbrains.kotlin:kotlin-stdlib-jdk7:${Versions.kotlin}"
    const val appcompat = "androidx.appcompat:appcompat:${Versions.appCompat}"
    const val constraintLayout = "androidx.constraintlayout:constraintlayout:${Versions.constraintLayout}"
    const val lifecycle = "androidx.lifecycle:lifecycle-extensions:${Versions.lifecycle}"
    const val lifecycleCompiler = "androidx.lifecycle:lifecycle-compiler:${Versions.lifecycle}"
    const val materialDesign = "com.google.android.material:material:${Versions.materialDesign}"
    const val rxJava = "io.reactivex.rxjava2:rxjava:2.2.7"
    const val rxAndroid = "io.reactivex.rxjava2:rxandroid:2.1.1"
    const val rxBinding = "com.jakewharton.rxbinding2:rxbinding:${Versions.rxBinding}"
    const val rxBindingAppCompat = "com.jakewharton.rxbinding2:rxbinding-appcompat:${Versions.rxBinding}"
    const val dagger = "com.google.dagger:dagger:${Versions.dagger}"
    const val daggerAndroid = "com.google.dagger:dagger-android-support:${Versions.dagger}"
    const val daggerCompiler = "com.google.dagger:dagger-compiler:${Versions.dagger}"
    const val daggerProcessor = "com.google.dagger:dagger-android-processor:${Versions.dagger}"
    const val annotations = "androidx.annotation:annotation:1.0.0"
    const val retrofit = "com.squareup.retrofit2:retrofit:${Versions.retrofit}"
    const val retrofitGsonConverter = "com.squareup.retrofit2:converter-gson:${Versions.retrofit}"
    const val retrofitRxJava2Adapter = "com.squareup.retrofit2:adapter-rxjava2:${Versions.retrofit}"
    const val okhttpLoggingInterceptor = "com.squareup.okhttp3:logging-interceptor:${Versions.okhttpLoggingInterceptor}"
    const val picasso = "com.squareup.picasso:picasso:${Versions.picasso}"
    const val picassoDownloader = "com.jakewharton.picasso:picasso2-okhttp3-downloader:${Versions.picassoDownloader}"

    const val junit = "junit:junit:${Versions.junit}"
    const val mockito = "com.nhaarman:mockito-kotlin:${Versions.mockito}"
    const val dexmaker = "com.linkedin.dexmaker:dexmaker-mockito:2.19.0"

    const val testRunner = "androidx.test:runner:${Versions.testRunner}"
    const val espresso = "androidx.test.espresso:espresso-core:${Versions.espresso}"

}